// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chainedCz.proto

package com.zhjl.tech.common.chained.protobuf.chainobj.v1;

public final class ChainedCz {
  private ChainedCz() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CzOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.Cz)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
     * / the version right now is '1'
     * </pre>
     *
     * <code>string version = 1;</code>
     */
    String getVersion();
    /**
     * <pre>
     *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
     * / the version right now is '1'
     * </pre>
     *
     * <code>string version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     ** [上链数据]订单号,全平台唯一标识. size=18
     * </pre>
     *
     * <code>string ordersn = 2;</code>
     */
    String getOrdersn();
    /**
     * <pre>
     ** [上链数据]订单号,全平台唯一标识. size=18
     * </pre>
     *
     * <code>string ordersn = 2;</code>
     */
    com.google.protobuf.ByteString
        getOrdersnBytes();

    /**
     * <pre>
     *是否过期。 0否，1是 
     * </pre>
     *
     * <code>string expired = 3;</code>
     */
    String getExpired();
    /**
     * <pre>
     *是否过期。 0否，1是 
     * </pre>
     *
     * <code>string expired = 3;</code>
     */
    com.google.protobuf.ByteString
        getExpiredBytes();

    /**
     * <pre>
     **存证详情的json串。类型参见czDetail. json编码后的base编码形式 
     * </pre>
     *
     * <code>bytes detail = 4;</code>
     */
    com.google.protobuf.ByteString getDetail();
  }
  /**
   * Protobuf type {@code com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.Cz}
   */
  public  static final class Cz extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.Cz)
      CzOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cz.newBuilder() to construct.
    private Cz(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cz() {
      version_ = "";
      ordersn_ = "";
      expired_ = "";
      detail_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cz(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              ordersn_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              expired_ = s;
              break;
            }
            case 34: {

              detail_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cz.class, Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private volatile Object version_;
    /**
     * <pre>
     *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
     * / the version right now is '1'
     * </pre>
     *
     * <code>string version = 1;</code>
     */
    @Override
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
     * / the version right now is '1'
     * </pre>
     *
     * <code>string version = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERSN_FIELD_NUMBER = 2;
    private volatile Object ordersn_;
    /**
     * <pre>
     ** [上链数据]订单号,全平台唯一标识. size=18
     * </pre>
     *
     * <code>string ordersn = 2;</code>
     */
    @Override
    public String getOrdersn() {
      Object ref = ordersn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ordersn_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** [上链数据]订单号,全平台唯一标识. size=18
     * </pre>
     *
     * <code>string ordersn = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getOrdersnBytes() {
      Object ref = ordersn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ordersn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRED_FIELD_NUMBER = 3;
    private volatile Object expired_;
    /**
     * <pre>
     *是否过期。 0否，1是 
     * </pre>
     *
     * <code>string expired = 3;</code>
     */
    @Override
    public String getExpired() {
      Object ref = expired_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        expired_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *是否过期。 0否，1是 
     * </pre>
     *
     * <code>string expired = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getExpiredBytes() {
      Object ref = expired_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        expired_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DETAIL_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString detail_;
    /**
     * <pre>
     **存证详情的json串。类型参见czDetail. json编码后的base编码形式 
     * </pre>
     *
     * <code>bytes detail = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString getDetail() {
      return detail_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
          return true;
      }
      if (isInitialized == 0) {
          return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
      }
      if (!getOrdersnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ordersn_);
      }
      if (!getExpiredBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, expired_);
      }
      if (!detail_.isEmpty()) {
        output.writeBytes(4, detail_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
          return size;
      }

      size = 0;
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
      }
      if (!getOrdersnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ordersn_);
      }
      if (!getExpiredBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, expired_);
      }
      if (!detail_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, detail_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Cz)) {
        return super.equals(obj);
      }
      Cz other = (Cz) obj;

      boolean result = true;
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && getOrdersn()
          .equals(other.getOrdersn());
      result = result && getExpired()
          .equals(other.getExpired());
      result = result && getDetail()
          .equals(other.getDetail());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + ORDERSN_FIELD_NUMBER;
      hash = (53 * hash) + getOrdersn().hashCode();
      hash = (37 * hash) + EXPIRED_FIELD_NUMBER;
      hash = (53 * hash) + getExpired().hashCode();
      hash = (37 * hash) + DETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getDetail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Cz parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cz parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cz parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cz parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cz parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cz parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cz parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cz parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cz parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Cz parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Cz parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Cz parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Cz prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.Cz}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.Cz)
        CzOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cz.class, Builder.class);
      }

      // Construct using com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.ChainedCz.Cz.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        version_ = "";

        ordersn_ = "";

        expired_ = "";

        detail_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_descriptor;
      }

      @Override
      public Cz getDefaultInstanceForType() {
        return Cz.getDefaultInstance();
      }

      @Override
      public Cz build() {
        Cz result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Cz buildPartial() {
        Cz result = new Cz(this);
        result.version_ = version_;
        result.ordersn_ = ordersn_;
        result.expired_ = expired_;
        result.detail_ = detail_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cz) {
          return mergeFrom((Cz)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cz other) {
        if (other == Cz.getDefaultInstance()) {
            return this;
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getOrdersn().isEmpty()) {
          ordersn_ = other.ordersn_;
          onChanged();
        }
        if (!other.getExpired().isEmpty()) {
          expired_ = other.expired_;
          onChanged();
        }
        if (other.getDetail() != com.google.protobuf.ByteString.EMPTY) {
          setDetail(other.getDetail());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cz parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cz) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object version_ = "";
      /**
       * <pre>
       *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
       * / the version right now is '1'
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      @Override
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
       * / the version right now is '1'
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
       * / the version right now is '1'
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
       * / the version right now is '1'
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;/[上链数据]存证记录版本。格式：1-2^16递增版本号.版本号与字典有关联
       * / the version right now is '1'
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private Object ordersn_ = "";
      /**
       * <pre>
       ** [上链数据]订单号,全平台唯一标识. size=18
       * </pre>
       *
       * <code>string ordersn = 2;</code>
       */
      @Override
      public String getOrdersn() {
        Object ref = ordersn_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ordersn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       ** [上链数据]订单号,全平台唯一标识. size=18
       * </pre>
       *
       * <code>string ordersn = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getOrdersnBytes() {
        Object ref = ordersn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ordersn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** [上链数据]订单号,全平台唯一标识. size=18
       * </pre>
       *
       * <code>string ordersn = 2;</code>
       */
      public Builder setOrdersn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ordersn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** [上链数据]订单号,全平台唯一标识. size=18
       * </pre>
       *
       * <code>string ordersn = 2;</code>
       */
      public Builder clearOrdersn() {
        
        ordersn_ = getDefaultInstance().getOrdersn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** [上链数据]订单号,全平台唯一标识. size=18
       * </pre>
       *
       * <code>string ordersn = 2;</code>
       */
      public Builder setOrdersnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ordersn_ = value;
        onChanged();
        return this;
      }

      private Object expired_ = "";
      /**
       * <pre>
       *是否过期。 0否，1是 
       * </pre>
       *
       * <code>string expired = 3;</code>
       */
      @Override
      public String getExpired() {
        Object ref = expired_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          expired_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *是否过期。 0否，1是 
       * </pre>
       *
       * <code>string expired = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getExpiredBytes() {
        Object ref = expired_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          expired_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *是否过期。 0否，1是 
       * </pre>
       *
       * <code>string expired = 3;</code>
       */
      public Builder setExpired(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        expired_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否过期。 0否，1是 
       * </pre>
       *
       * <code>string expired = 3;</code>
       */
      public Builder clearExpired() {
        
        expired_ = getDefaultInstance().getExpired();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否过期。 0否，1是 
       * </pre>
       *
       * <code>string expired = 3;</code>
       */
      public Builder setExpiredBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        expired_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString detail_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       **存证详情的json串。类型参见czDetail. json编码后的base编码形式 
       * </pre>
       *
       * <code>bytes detail = 4;</code>
       */
      @Override
      public com.google.protobuf.ByteString getDetail() {
        return detail_;
      }
      /**
       * <pre>
       **存证详情的json串。类型参见czDetail. json编码后的base编码形式 
       * </pre>
       *
       * <code>bytes detail = 4;</code>
       */
      public Builder setDetail(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        detail_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **存证详情的json串。类型参见czDetail. json编码后的base编码形式 
       * </pre>
       *
       * <code>bytes detail = 4;</code>
       */
      public Builder clearDetail() {
        
        detail_ = getDefaultInstance().getDetail();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.Cz)
    }

    // @@protoc_insertion_point(class_scope:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.Cz)
    private static final Cz DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Cz();
    }

    public static Cz getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cz>
        PARSER = new com.google.protobuf.AbstractParser<Cz>() {
      @Override
      public Cz parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cz(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cz> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Cz> getParserForType() {
      return PARSER;
    }

    @Override
    public Cz getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CzDetail_1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.CzDetail_1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     *订单信息的hash值，采用sm3生成，然后采用base64编码。
     *hash的生成方式参见对应版本对象的usage说明。
     * </pre>
     *
     * <code>bytes hash = 1;</code>
     */
    com.google.protobuf.ByteString getHash();
  }
  /**
   * <pre>
   *存证详细内容. endfix is '_1' means that it is the first edition of CzDetail
   * </pre>
   *
   * Protobuf type {@code com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.CzDetail_1}
   */
  public  static final class CzDetail_1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.CzDetail_1)
      CzDetail_1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CzDetail_1.newBuilder() to construct.
    private CzDetail_1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CzDetail_1() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CzDetail_1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              hash_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CzDetail_1.class, Builder.class);
    }

    public static final int HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString hash_;
    /**
     * <pre>
     **
     *订单信息的hash值，采用sm3生成，然后采用base64编码。
     *hash的生成方式参见对应版本对象的usage说明。
     * </pre>
     *
     * <code>bytes hash = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
          return true;
      }
      if (isInitialized == 0) {
          return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!hash_.isEmpty()) {
        output.writeBytes(1, hash_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
          return size;
      }

      size = 0;
      if (!hash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, hash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CzDetail_1)) {
        return super.equals(obj);
      }
      CzDetail_1 other = (CzDetail_1) obj;

      boolean result = true;
      result = result && getHash()
          .equals(other.getHash());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CzDetail_1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CzDetail_1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CzDetail_1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CzDetail_1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CzDetail_1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CzDetail_1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CzDetail_1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CzDetail_1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CzDetail_1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CzDetail_1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CzDetail_1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CzDetail_1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CzDetail_1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *存证详细内容. endfix is '_1' means that it is the first edition of CzDetail
     * </pre>
     *
     * Protobuf type {@code com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.CzDetail_1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.CzDetail_1)
        CzDetail_1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CzDetail_1.class, Builder.class);
      }

      // Construct using com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.ChainedCz.CzDetail_1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        hash_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChainedCz.internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_descriptor;
      }

      @Override
      public CzDetail_1 getDefaultInstanceForType() {
        return CzDetail_1.getDefaultInstance();
      }

      @Override
      public CzDetail_1 build() {
        CzDetail_1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CzDetail_1 buildPartial() {
        CzDetail_1 result = new CzDetail_1(this);
        result.hash_ = hash_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CzDetail_1) {
          return mergeFrom((CzDetail_1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CzDetail_1 other) {
        if (other == CzDetail_1.getDefaultInstance()) {
            return this;
        }
        if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
          setHash(other.getHash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CzDetail_1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CzDetail_1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       **
       *订单信息的hash值，采用sm3生成，然后采用base64编码。
       *hash的生成方式参见对应版本对象的usage说明。
       * </pre>
       *
       * <code>bytes hash = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <pre>
       **
       *订单信息的hash值，采用sm3生成，然后采用base64编码。
       *hash的生成方式参见对应版本对象的usage说明。
       * </pre>
       *
       * <code>bytes hash = 1;</code>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *订单信息的hash值，采用sm3生成，然后采用base64编码。
       *hash的生成方式参见对应版本对象的usage说明。
       * </pre>
       *
       * <code>bytes hash = 1;</code>
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.CzDetail_1)
    }

    // @@protoc_insertion_point(class_scope:com.zhjl.tech.store.chainedCallBack.protobuf.chainobj.v1.CzDetail_1)
    private static final CzDetail_1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CzDetail_1();
    }

    public static CzDetail_1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CzDetail_1>
        PARSER = new com.google.protobuf.AbstractParser<CzDetail_1>() {
      @Override
      public CzDetail_1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CzDetail_1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CzDetail_1> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CzDetail_1> getParserForType() {
      return PARSER;
    }

    @Override
    public CzDetail_1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017chainedCz.proto\0220com.zhjl.tech.store.c" +
      "hained.protobuf.chainobj.v1\"G\n\002Cz\022\017\n\007ver" +
      "sion\030\001 \001(\t\022\017\n\007ordersn\030\002 \001(\t\022\017\n\007expired\030\003" +
      " \001(\t\022\016\n\006detail\030\004 \001(\014\"\032\n\nCzDetail_1\022\014\n\004ha" +
      "sh\030\001 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          @Override
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_Cz_descriptor,
        new String[] { "Version", "Ordersn", "Expired", "Detail", });
    internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhjl_tech_store_chained_protobuf_chainobj_v1_CzDetail_1_descriptor,
        new String[] { "Hash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
